export const environment = {
  PRODUCTION: false,
  //API_URL: 'http://localhost:3009/',
  API_URL: 'https://veterinaria-back-5ca7aec509fb.herokuapp.com/',
  USUARIO_ENDPOINT: 'Usuarios',
  ROL_ENDPOINT: 'Rols',
  CLIENTE_ENDPOINT: 'Clientes',
  MASCOTA_ENDPOINT: 'Mascotas',
  SEXO_ENDPOINT:'Sexos',
  ESPECIE_ENDPOINT:'Especies',
  RAZA_ENDPOINT:'Razas',
  PROVEEDOR_ENDPOINT: 'Proveedors',
  CATEGORIA_PRODUCTO_ENDPOINT: 'Categoria_productos',
  PRODUCTO_ENDPOINT: 'Productos',
  COMPRA_ENDPOINT: 'Compras',
  DETALLE_COMPRA_ENDPOINT: 'Detalle_compras',
  VENTA_ENDPOINT: 'Ventas',
  DETALLE_VENTA_ENDPOINT: 'Detalle_ventas',
  HISTORIA_CLINICA_ENDPOINT: 'Historia_clinicas',
  REPORTE_ENDPOINT: 'Reportes',
  PAGO_ENDPOINT: 'Pagos',
  PAGE_ENDPOINT: 'Pages',
  ACCESO_ENDPOINT: 'Accesos'
};

